### ISSUE TITLE
Can't run android example. 

### ISSUE THREAD

**Issue by benevbright** [nidorx/react-native-colibri#1]
Hi, I saw your comment here https://github.com/facebook/react-native/issues/21801#issuecomment-525988900
I really appreciate. 

So, I wanted to run your example but I can't run it. 
I got this error from `react-native run-android`.
I can't run it on Android Studio as well. 

I tried to do `./gradlew clean` in `android` folder but I got a permission error.
Any idea?

Of course, I'm able to run several other RN projects but this one is not working for me.

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 968 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: spawnSync ./gradlew EACCES
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices 
```

**Comment by benevbright** [comment]
https://stackoverflow.com/questions/54541734/spawnsync-gradlew-eacces-error-when-running-react-native-project-on-emulator-u

Looks like file permission is wrong.

**Comment by nidorx** [comment]
chmod 755 android/gradlew
